import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :whisperlogs, WhisperLogsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Disable detailed error pages in production - show generic errors only
  debug_errors: false

# SSL is handled by reverse proxy in production deployments.
# For standalone/SQLite mode, we don't force SSL since it's typically local.
# Uncomment below if you want to force SSL (requires proper cert setup):
#
# config :whisperlogs, WhisperLogsWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]],
#   exclude: [hosts: ["localhost", "127.0.0.1"]]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
